#!/bin/sh


run_marlin_arbor_usage () 
{
    echo "Usage : RunMarlinArbor marlin.xml lcioFile.slcio gearFile.xml pandoraXmlFile.xml [outputFileName.slcio]"
    exit 1
}

if [ $# -lt 4 ]
then
    echo "Wrong number of arguments"
    run_marlin_arbor_usage
fi


marlinXml=$1
lcioFile=$2
gearFile=$3
pandoraFile=$4
outputFileName="output.slcio"

if [ $# -eq 5 ]
then
	outputFileName=$5
fi



echo $MARLIN_DLL

# run marlin !
echo "Running Marlin Arbor (full reco)"
Marlin --global.GearXMLFile=$gearFile --global.LCIOInputFiles=$lcioFile --MyMarlinArbor.PandoraSettingsXmlFile=$pandoraFile --MyLCIOOutputProcessor.LCIOOutputFile=$outputFileName $marlinXml

status=$?

if [ $status != 0 ]
then
    echo "Exiting ! Error caught is $status"
    exit 1
fi

